# 对外端口
server:
  port: 9000

spring:
  # 应用名
  application:
    name: gateway
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  # cloud配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8721
        dashboard: 127.0.0.1:8080
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: SERVICE-ITEM
          uri: lb://service-item
          predicates:
            # 路径匹配，以 api 开头，直接配置是不生效的，看 filters 配置
            - Path=/api/item/**
          filters:
            # 前缀过滤，默认配置下，我们的请求路径是 http://localhost:9000/service-consumer-item/** 这时会路由到指定的服务
            # 此处配置去掉 1 个路径前缀，再配置上面的 Path=/api/**，就能按照 http://localhost:9000/api/** 的方式访问了
            - StripPrefix=1
        - id: SERVICE-USER
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
  main:
    # 允许覆盖重写
    allow-bean-definition-overriding: true

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    com.tiny: debug
