server:
  port: 9500
  servlet:
    context-path: /api/search

logging:
  level:
    root: info
    com.tiny.service.search: debug

spring:
  application:
    name: service-search
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-alibaba-template?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  # cloud alibaba config
  cloud:
    # Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    # Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

## 开启 sentinel 对 feign
#feign:
#  sentinel:
#    enabled: true
